name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "15 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Shanghai
          config_twemoji: true
          config_octicon: true
          config_display: large
          base: header, activity, community, repositories, metadata
          base_indepth: false
          base_hireable: false
          base_skip: false
          
          
